import 'package:ridge/features/profile/presentation/keyboard_shape_family.dart';

/// Curated `keyboardModel` string → [KeyboardShapeFamily] classification,
/// one entry per non-`'Other'` value in `kKeyboardModelSuggestions`
/// (`profile_suggestions.dart`), classified from each product's publicly
/// published key count/layout (numpad present? function row? split?) —
/// never a guess from the brand name alone. A handful of ambiguous
/// multi-SKU names (e.g. a model sold in both TKL and full-size trims
/// under the same name) resolve to their most common/flagship trim; this
/// is a decorative "generic family" illustration, not a spec sheet.
///
/// `test/features/profile/keyboard_shape_lookup_test.dart` asserts every
/// `kKeyboardModelSuggestions` entry except `'Other'` has a mapping here,
/// so a future addition to that suggestion list can't silently ship
/// unclassified.
const Map<String, KeyboardShapeFamily> _keyboardShapeFamilyByModel = {
  'Ajazz AK33': KeyboardShapeFamily.seventyFive,
  'Ajazz AK820': KeyboardShapeFamily.tkl,
  'Akko 3068B': KeyboardShapeFamily.sixtyFive,
  'Akko 5075B': KeyboardShapeFamily.seventyFive,
  'Akko 5108B': KeyboardShapeFamily.fullSize,
  'Akko ACR Pro 75': KeyboardShapeFamily.seventyFive,
  'Akko MOD007': KeyboardShapeFamily.seventyFive,
  'Anne Pro 2': KeyboardShapeFamily.sixty,
  'Anne Pro 3': KeyboardShapeFamily.sixty,
  'Apple Magic Keyboard': KeyboardShapeFamily.tkl,
  'Apple Magic Keyboard with Touch ID': KeyboardShapeFamily.tkl,
  'ASUS ROG Azoth': KeyboardShapeFamily.seventyFive,
  'ASUS ROG Falchion': KeyboardShapeFamily.sixtyFive,
  'ASUS ROG Strix Scope': KeyboardShapeFamily.fullSize,
  'Attack Shark K86': KeyboardShapeFamily.tkl,
  'Attack Shark X3': KeyboardShapeFamily.fullSize,
  'Cooler Master CK720': KeyboardShapeFamily.sixtyFive,
  'Cooler Master MK770': KeyboardShapeFamily.fullSize,
  'Cooler Master SK650': KeyboardShapeFamily.tkl,
  'Corsair K55': KeyboardShapeFamily.fullSize,
  'Corsair K65 Mini': KeyboardShapeFamily.sixty,
  'Corsair K70 RGB': KeyboardShapeFamily.fullSize,
  'Corsair K95 RGB Platinum': KeyboardShapeFamily.fullSize,
  'Corsair K100': KeyboardShapeFamily.fullSize,
  'Das Keyboard 4 Professional': KeyboardShapeFamily.fullSize,
  'Das Keyboard 5Q': KeyboardShapeFamily.fullSize,
  'Das Keyboard Model S': KeyboardShapeFamily.fullSize,
  'Drop ALT': KeyboardShapeFamily.sixtyFive,
  'Drop CTRL': KeyboardShapeFamily.tkl,
  'Ducky Mecha Mini': KeyboardShapeFamily.sixty,
  'Ducky One 2': KeyboardShapeFamily.fullSize,
  'Ducky One 2 Mini': KeyboardShapeFamily.sixty,
  'Ducky One 2 SF': KeyboardShapeFamily.sixtyFive,
  'Ducky One 3': KeyboardShapeFamily.fullSize,
  'Ducky One 3 Mini': KeyboardShapeFamily.sixty,
  'Ducky One 3 SF': KeyboardShapeFamily.sixtyFive,
  'Ducky Shine 7': KeyboardShapeFamily.fullSize,
  'Ducky Zero': KeyboardShapeFamily.fullSize,
  'Epomaker GK96S': KeyboardShapeFamily.fullSize,
  'Epomaker TH66': KeyboardShapeFamily.sixtyFive,
  'Epomaker TH80': KeyboardShapeFamily.seventyFive,
  'Epomaker TH96': KeyboardShapeFamily.fullSize,
  'ErgoDox EZ': KeyboardShapeFamily.splitErgo,
  'ErgoDox EZ Glow': KeyboardShapeFamily.splitErgo,
  'Filco Majestouch 2': KeyboardShapeFamily.fullSize,
  'Filco Majestouch Minila': KeyboardShapeFamily.sixty,
  'Glorious GMMK 2': KeyboardShapeFamily.fullSize,
  'Glorious GMMK Compact': KeyboardShapeFamily.sixty,
  'Glorious GMMK Numpad': KeyboardShapeFamily.sixty,
  'Glorious GMMK Pro': KeyboardShapeFamily.seventyFive,
  'HHKB Professional Classic': KeyboardShapeFamily.sixty,
  'HHKB Professional Hybrid': KeyboardShapeFamily.sixty,
  'HHKB Studio': KeyboardShapeFamily.sixty,
  'IBM Model F': KeyboardShapeFamily.fullSize,
  'IBM Model M': KeyboardShapeFamily.fullSize,
  'Kinesis Advantage2': KeyboardShapeFamily.splitErgo,
  'Kinesis Advantage360': KeyboardShapeFamily.splitErgo,
  'Kinesis Freestyle Edge': KeyboardShapeFamily.splitErgo,
  'Keychron C1': KeyboardShapeFamily.tkl,
  'Keychron C2': KeyboardShapeFamily.fullSize,
  'Keychron K Pro': KeyboardShapeFamily.tkl,
  'Keychron K2': KeyboardShapeFamily.seventyFive,
  'Keychron K3': KeyboardShapeFamily.seventyFive,
  'Keychron K4': KeyboardShapeFamily.fullSize,
  'Keychron K6': KeyboardShapeFamily.sixtyFive,
  'Keychron K8': KeyboardShapeFamily.tkl,
  'Keychron K8 Pro': KeyboardShapeFamily.tkl,
  'Keychron K10': KeyboardShapeFamily.fullSize,
  'Keychron K10 Pro': KeyboardShapeFamily.fullSize,
  'Keychron Q1': KeyboardShapeFamily.seventyFive,
  'Keychron Q1 HE': KeyboardShapeFamily.seventyFive,
  'Keychron Q2': KeyboardShapeFamily.sixtyFive,
  'Keychron Q3': KeyboardShapeFamily.tkl,
  'Keychron Q3 Max': KeyboardShapeFamily.tkl,
  'Keychron Q5': KeyboardShapeFamily.fullSize,
  'Keychron Q6': KeyboardShapeFamily.fullSize,
  'Keychron Q10': KeyboardShapeFamily.seventyFive,
  'Keychron Q11': KeyboardShapeFamily.fullSize,
  'Keychron V1': KeyboardShapeFamily.seventyFive,
  'Keychron V3': KeyboardShapeFamily.tkl,
  'Keychron V6': KeyboardShapeFamily.fullSize,
  'Keychron V10': KeyboardShapeFamily.fullSize,
  'Leopold FC660M': KeyboardShapeFamily.sixtyFive,
  'Leopold FC750R': KeyboardShapeFamily.tkl,
  'Leopold FC900R': KeyboardShapeFamily.fullSize,
  'Leopold FC980M': KeyboardShapeFamily.fullSize,
  'Logitech G413': KeyboardShapeFamily.fullSize,
  'Logitech G915': KeyboardShapeFamily.fullSize,
  'Logitech G Pro X': KeyboardShapeFamily.tkl,
  'Logitech K380': KeyboardShapeFamily.tkl,
  'Logitech MX Keys': KeyboardShapeFamily.fullSize,
  'Logitech MX Keys Mini': KeyboardShapeFamily.seventyFive,
  'Logitech MX Mechanical': KeyboardShapeFamily.fullSize,
  'Logitech POP Keys': KeyboardShapeFamily.seventyFive,
  'MCHOSE ACE60': KeyboardShapeFamily.sixty,
  'MCHOSE ACE68': KeyboardShapeFamily.sixtyFive,
  'MCHOSE G68': KeyboardShapeFamily.sixtyFive,
  'MCHOSE G75': KeyboardShapeFamily.seventyFive,
  'MCHOSE G96': KeyboardShapeFamily.fullSize,
  'Monsgeek Fun60': KeyboardShapeFamily.sixty,
  'Monsgeek M1': KeyboardShapeFamily.seventyFive,
  'Monsgeek M3': KeyboardShapeFamily.tkl,
  'MSI Vigor GK50': KeyboardShapeFamily.tkl,
  'MSI Vigor GK71': KeyboardShapeFamily.fullSize,
  'NuPhy Air60': KeyboardShapeFamily.sixty,
  'NuPhy Air75': KeyboardShapeFamily.seventyFive,
  'NuPhy Air96': KeyboardShapeFamily.fullSize,
  'NuPhy Halo65': KeyboardShapeFamily.sixtyFive,
  'NuPhy Halo75': KeyboardShapeFamily.seventyFive,
  'Razer BlackWidow V3': KeyboardShapeFamily.fullSize,
  'Razer BlackWidow V4': KeyboardShapeFamily.fullSize,
  'Razer DeathStalker V2': KeyboardShapeFamily.fullSize,
  'Razer Huntsman Mini': KeyboardShapeFamily.sixty,
  'Razer Huntsman V2': KeyboardShapeFamily.fullSize,
  'Razer Ornata V3': KeyboardShapeFamily.fullSize,
  'Redragon K530 Draconic': KeyboardShapeFamily.sixty,
  'Redragon K552 Kumara': KeyboardShapeFamily.tkl,
  'Redragon K617 Fizz': KeyboardShapeFamily.sixty,
  'Royal Kludge RK61': KeyboardShapeFamily.sixty,
  'Royal Kludge RK68': KeyboardShapeFamily.sixtyFive,
  'Royal Kludge RK84': KeyboardShapeFamily.seventyFive,
  'Royal Kludge RK96': KeyboardShapeFamily.fullSize,
  'Royal Kludge RK100': KeyboardShapeFamily.fullSize,
  'Realforce R2': KeyboardShapeFamily.fullSize,
  'Realforce R3': KeyboardShapeFamily.fullSize,
  'Realforce R3S': KeyboardShapeFamily.fullSize,
  'Skyloong GK61': KeyboardShapeFamily.sixty,
  'Skyloong GK75': KeyboardShapeFamily.seventyFive,
  'Skyloong GK96': KeyboardShapeFamily.fullSize,
  'SteelSeries Apex 3': KeyboardShapeFamily.fullSize,
  'SteelSeries Apex 7': KeyboardShapeFamily.fullSize,
  'SteelSeries Apex Pro': KeyboardShapeFamily.fullSize,
  'SteelSeries Apex Pro Mini': KeyboardShapeFamily.sixty,
  'Topre Realforce 87U': KeyboardShapeFamily.tkl,
  'Topre Type Heaven': KeyboardShapeFamily.tkl,
  'Varmilo Minilo': KeyboardShapeFamily.sixtyFive,
  'Varmilo VA87M': KeyboardShapeFamily.tkl,
  'Varmilo VA108M': KeyboardShapeFamily.fullSize,
  'Varmilo VA109M': KeyboardShapeFamily.fullSize,
  'Vortex POK3R': KeyboardShapeFamily.sixty,
  'Vortex Race 3': KeyboardShapeFamily.seventyFive,
  'Vortex Tab 60': KeyboardShapeFamily.sixty,
  'WASD CODE': KeyboardShapeFamily.tkl,
  'WASD V3': KeyboardShapeFamily.fullSize,
  'Womier K66': KeyboardShapeFamily.sixtyFive,
  'Womier K87': KeyboardShapeFamily.tkl,
  'Wooting 60HE': KeyboardShapeFamily.sixty,
  'Wooting 80HE': KeyboardShapeFamily.seventyFive,
  'Wooting Two HE': KeyboardShapeFamily.tkl,
  'ZSA Moonlander Mark I': KeyboardShapeFamily.splitErgo,
  'ZSA Voyager': KeyboardShapeFamily.splitErgo,
};

/// The [KeyboardShapeFamily] to illustrate for a profile's free-text
/// `keyboardModel`, or `null` when [model] is empty, `'Other'`, or isn't
/// one of the curated `kKeyboardModelSuggestions` values — the caller
/// should render nothing in that case rather than guess a shape.
KeyboardShapeFamily? keyboardShapeFamilyFor(String? model) {
  if (model == null || model.isEmpty) return null;
  return _keyboardShapeFamilyByModel[model];
}
