/// Curated autocomplete candidates for the profile editor's free-text
/// fields — purely UI suggestion data (not a closed set: the user can
/// still type anything, these just make common values fast to complete),
/// so this lives in `presentation`, not `domain`.
///
/// Kept as flat, alphabetized `const` lists on purpose: a handful of
/// hundred short strings is cheap to filter with a single linear
/// `.where()` pass on every keystroke (`_SuggestionField` in
/// `edit_profile_screen.dart` also caps the match count it renders), so
/// there's no need for an index/trie here — that would be complexity
/// this data size doesn't earn.
library;

/// Well-known keyboard brands — general-purpose, gaming, and
/// mechanical/enthusiast, spanning mainstream and boutique makers.
const kKeyboardBrandSuggestions = <String>[
  '8BitDo',
  'Ajazz',
  'Akko',
  'Alienware',
  'Anne Pro',
  'Apple',
  'ASUS ROG',
  'Attack Shark',
  'Aula',
  'Autonomous',
  'Bloody (A4Tech)',
  'Cherry',
  'Cooler Master',
  'CoolKiller',
  'Corsair',
  'Custom/homemade',
  'Dareu',
  'Das Keyboard',
  'Dell',
  'Drevo',
  'Drop (Massdrop)',
  'Ducky',
  'Durgod',
  'Dygma',
  'Epomaker',
  'ErgoDox EZ',
  'Feker',
  'Filco',
  'FL Esports',
  'Fnatic',
  'Genesis',
  'Glorious (GMMK)',
  'Havit',
  'HHKB (Happy Hacking)',
  'HP',
  'HyperX',
  'IBM Model M',
  'iKBC',
  'Iqunix',
  'Jamesdonkey',
  'Kailh',
  'Keychron',
  'Keydous',
  'Keytron',
  'Kinesis',
  'Lenovo',
  'Leopold',
  'Lofree',
  'Logitech',
  'Logitech G',
  'Machenike',
  'Magicforce',
  'MCHOSE',
  'Microsoft',
  'Monsgeek',
  'MSI',
  'NACON',
  'Newmen',
  'Ninkear',
  'Noppoo',
  'NuPhy',
  'Obins',
  'Onikuma',
  'Owlab',
  'Percent (GK64/GK61)',
  'Planck',
  'Qisan',
  'Rapoo',
  'Razer',
  'Red Square',
  'Redragon',
  'Roccat',
  'Royal Kludge (RK)',
  'Sades',
  'Skyloong',
  'SteelSeries',
  'Tecware',
  'Tesoro',
  'Thermaltake',
  'Topre',
  'Unicomp',
  'Varmilo',
  'Vortex',
  'VXE',
  'WASD Keyboards',
  'Womier',
  'Wooting',
  'Xtrfy',
  'YMDK',
  'Zeno',
  'Zifriend',
  'Zoom75',
  'ZSA (ErgoDox/Moonlander/Voyager)',
  'Other',
];

/// Well-known keyboard models across those brands.
const kKeyboardModelSuggestions = <String>[
  'Ajazz AK33',
  'Ajazz AK820',
  'Akko 3068B',
  'Akko 5075B',
  'Akko 5108B',
  'Akko ACR Pro 75',
  'Akko MOD007',
  'Anne Pro 2',
  'Anne Pro 3',
  'Apple Magic Keyboard',
  'Apple Magic Keyboard with Touch ID',
  'ASUS ROG Azoth',
  'ASUS ROG Falchion',
  'ASUS ROG Strix Scope',
  'Attack Shark K86',
  'Attack Shark X3',
  'Cooler Master CK720',
  'Cooler Master MK770',
  'Cooler Master SK650',
  'Corsair K55',
  'Corsair K65 Mini',
  'Corsair K70 RGB',
  'Corsair K95 RGB Platinum',
  'Corsair K100',
  'Das Keyboard 4 Professional',
  'Das Keyboard 5Q',
  'Das Keyboard Model S',
  'Drop ALT',
  'Drop CTRL',
  'Ducky Mecha Mini',
  'Ducky One 2',
  'Ducky One 2 Mini',
  'Ducky One 2 SF',
  'Ducky One 3',
  'Ducky One 3 Mini',
  'Ducky One 3 SF',
  'Ducky Shine 7',
  'Ducky Zero',
  'Epomaker GK96S',
  'Epomaker TH66',
  'Epomaker TH80',
  'Epomaker TH96',
  'ErgoDox EZ',
  'ErgoDox EZ Glow',
  'Filco Majestouch 2',
  'Filco Majestouch Minila',
  'Glorious GMMK 2',
  'Glorious GMMK Compact',
  'Glorious GMMK Numpad',
  'Glorious GMMK Pro',
  'HHKB Professional Classic',
  'HHKB Professional Hybrid',
  'HHKB Studio',
  'IBM Model F',
  'IBM Model M',
  'Kinesis Advantage2',
  'Kinesis Advantage360',
  'Kinesis Freestyle Edge',
  'Keychron C1',
  'Keychron C2',
  'Keychron K Pro',
  'Keychron K2',
  'Keychron K3',
  'Keychron K4',
  'Keychron K6',
  'Keychron K8',
  'Keychron K8 Pro',
  'Keychron K10',
  'Keychron K10 Pro',
  'Keychron Q1',
  'Keychron Q1 HE',
  'Keychron Q2',
  'Keychron Q3',
  'Keychron Q3 Max',
  'Keychron Q5',
  'Keychron Q6',
  'Keychron Q10',
  'Keychron Q11',
  'Keychron V1',
  'Keychron V3',
  'Keychron V6',
  'Keychron V10',
  'Leopold FC660M',
  'Leopold FC750R',
  'Leopold FC900R',
  'Leopold FC980M',
  'Logitech G413',
  'Logitech G915',
  'Logitech G Pro X',
  'Logitech K380',
  'Logitech MX Keys',
  'Logitech MX Keys Mini',
  'Logitech MX Mechanical',
  'Logitech POP Keys',
  'MCHOSE ACE60',
  'MCHOSE ACE68',
  'MCHOSE G68',
  'MCHOSE G75',
  'MCHOSE G96',
  'MCHOSE GX87',
  'Monsgeek Fun60',
  'Monsgeek M1',
  'Monsgeek M3',
  'MSI Vigor GK50',
  'MSI Vigor GK71',
  'NuPhy Air60',
  'NuPhy Air75',
  'NuPhy Air96',
  'NuPhy Halo65',
  'NuPhy Halo75',
  'Razer BlackWidow V3',
  'Razer BlackWidow V4',
  'Razer DeathStalker V2',
  'Razer Huntsman Mini',
  'Razer Huntsman V2',
  'Razer Ornata V3',
  'Redragon K530 Draconic',
  'Redragon K552 Kumara',
  'Redragon K617 Fizz',
  'Royal Kludge RK61',
  'Royal Kludge RK68',
  'Royal Kludge RK84',
  'Royal Kludge RK96',
  'Royal Kludge RK100',
  'Realforce R2',
  'Realforce R3',
  'Realforce R3S',
  'Skyloong GK61',
  'Skyloong GK75',
  'Skyloong GK96',
  'SteelSeries Apex 3',
  'SteelSeries Apex 7',
  'SteelSeries Apex Pro',
  'SteelSeries Apex Pro Mini',
  'Topre Realforce 87U',
  'Topre Type Heaven',
  'Varmilo Minilo',
  'Varmilo VA87M',
  'Varmilo VA108M',
  'Varmilo VA109M',
  'Vortex POK3R',
  'Vortex Race 3',
  'Vortex Tab 60',
  'WASD CODE',
  'WASD V3',
  'Womier K66',
  'Womier K87',
  'Wooting 60HE',
  'Wooting 80HE',
  'Wooting Two HE',
  'ZSA Moonlander Mark I',
  'ZSA Voyager',
  'Other',
];

/// Well-known programmers, computer scientists, and tech/dev influences —
/// language and framework creators, historical pioneers, open-source
/// maintainers, security researchers, and modern educators/streamers.
const kFavoriteProgrammerSuggestions = <String>[
  'Ada Lovelace',
  'Addy Osmani',
  'Alan Kay',
  'Alan Turing',
  'Alexey Kutepov (Tsoding)',
  'Andrej Karpathy',
  'Anders Hejlsberg',
  'Barbara Liskov',
  'Ben Awad',
  'Betty Holberton',
  'Bill Gates',
  'Bjarne Stroustrup',
  'Bob Kahn',
  'Brad Traversy',
  'Brendan Eich',
  'Brian Kernighan',
  'Bruce Schneier',
  'Charles Babbage',
  'Chris Lattner',
  'Claude Shannon',
  'Corey Schafer',
  'Daniel Shiffman (The Coding Train)',
  'Dan Abramov',
  'David Heinemeier Hansson',
  'Dennis Ritchie',
  'Donald Knuth',
  'Doug Engelbart',
  'Douglas Crockford',
  'Edsger Dijkstra',
  'Errichto (Kamil Dębowski)',
  'Fabrice Bellard',
  'Feross Aboukhadijeh',
  'Frances Allen',
  'George Hotz (geohot)',
  'Gennady Korotkevich (tourist)',
  'Grace Hopper',
  'Graydon Hoare',
  'Guido van Rossum',
  'Guillermo Rauch',
  'HD Moore',
  'Hedy Lamarr',
  'Ivan Sutherland',
  'James Gosling',
  'James Murphy (mCoding)',
  'Jean Bartik',
  'Jeff Dean',
  'Jeff Delaney (Fireship)',
  'John Carmack',
  'John McCarthy',
  'John Resig',
  'Jordan Walke',
  'Jose Valim',
  'Joseph Weizenbaum',
  'Karen Spärck Jones',
  'Katherine Johnson',
  'Katie Moussouris',
  'Kelsey Hightower',
  'Ken Thompson',
  'Kent Beck',
  'Kevin Mitnick',
  'Kevin Powell',
  'Kyle Cook (Web Dev Simplified)',
  'Larry Wall',
  'Linus Torvalds',
  'Margaret Hamilton',
  'Margaret Mitchell',
  'Marvin Minsky',
  'Martin Fowler',
  'Martin Odersky',
  'Mudge (Peiter Zatko)',
  'Niklaus Wirth',
  'Paul Irish',
  'Petr Mitrichev',
  'Quincy Larson (freeCodeCamp)',
  'Radia Perlman',
  'Rasmus Lerdorf',
  'Rebecca Murphey',
  'Rich Harris',
  'Rich Hickey',
  'Richard Stallman',
  'Robert C. Martin',
  'Rob Pike',
  'Roberto Ierusalimschy',
  'Ryan Dahl',
  'Sanjay Ghemawat',
  'Sean Wrona',
  'Sebastian Markbåge',
  'Seymour Papert',
  'Sindre Sorhus',
  'Solomon Hykes',
  'Steve Wozniak',
  'Taylor Otwell',
  'Tavis Ormandy',
  'Théo Browne (t3.gg)',
  'Tim Berners-Lee',
  'Tim Sweeney',
  'TJ Holowaychuk',
  'Travis Oliphant',
  'Troy Hunt',
  'Vannevar Bush',
  'Vint Cerf',
  'Werner Vogels',
  'Wes McKinney',
  'Yehuda Katz',
  'Yukihiro Matsumoto',
  'Other',
];
