import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

import 'package:ridge/core/i18n/gen/app_localizations.dart';
import 'package:ridge/core/widgets/escape_to_pop.dart';
import 'package:ridge/core/widgets/keyboard_scroll_shortcuts.dart';
import 'package:ridge/core/widgets/staggered_entrance.dart';

/// Displays the project's `CHANGELOG.md`, bundled as a Flutter asset so the
/// running app can show its own release history without anyone needing the
/// repo checked out. The file itself is generated by
/// `tool/version_bump.dart` from Conventional Commits (STACK.md §10.4) —
/// this screen only renders it, never edits it.
class ChangelogScreen extends StatelessWidget {
  /// Creates the changelog screen.
  const new({super.key});

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    return EscapeToPop(
      child: Scaffold(
        appBar: AppBar(title: Text(l10n.changelogScreenTitle)),
        body: FutureBuilder<String>(
          future: rootBundle.loadString('CHANGELOG.md'),
          builder: (context, snapshot) {
            if (snapshot.hasError) {
              return Center(child: Text(l10n.changelogLoadError));
            }
            if (!snapshot.hasData) {
              return const Center(child: CircularProgressIndicator());
            }
            return _ChangelogBody(markdown: snapshot.data!);
          },
        ),
      ),
    );
  }
}

class _ChangelogBody extends StatefulWidget {
  const new({required this.markdown});

  final String markdown;

  @override
  State<_ChangelogBody> createState() => _ChangelogBodyState();
}

class _ChangelogBodyState extends State<_ChangelogBody> {
  final _scrollController = ScrollController();

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final lines = _versionEntries(widget.markdown);
    return KeyboardScrollShortcuts(
      controller: _scrollController,
      child: ListView.builder(
        controller: _scrollController,
        padding: const EdgeInsets.all(16),
        itemCount: lines.length,
        itemBuilder: (context, index) {
          final line = _lineWidget(lines[index], theme, isFirst: index == 0);
          return index < 8 ? line.staggeredIn(context, index) : line;
        },
      ),
    );
  }

  /// Drops the doc preamble (title + boilerplate paragraph) and starts
  /// rendering at the first version heading, e.g. `## [1.7.0] - 2026-09-10`.
  List<String> _versionEntries(String markdown) {
    final lines = markdown.split('\n');
    final start = lines.indexWhere((line) => line.startsWith('## ['));
    return start == -1 ? lines : lines.sublist(start);
  }

  Widget _lineWidget(String line, ThemeData theme, {required bool isFirst}) {
    if (line.startsWith('## ')) {
      final heading = line.substring(3);
      final match = RegExp(r'^\[(.+?)\]\s*-\s*(.+)$').firstMatch(heading);
      return Padding(
        padding: EdgeInsets.only(top: isFirst ? 0 : 24, bottom: 8),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            if (!isFirst) const Divider(height: 25),
            Row(
              crossAxisAlignment: CrossAxisAlignment.baseline,
              textBaseline: TextBaseline.alphabetic,
              children: [
                Text(
                  match?.group(1) ?? heading,
                  style: theme.textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
                if (match != null) ...[
                  const SizedBox(width: 8),
                  Text(
                    match.group(2)!,
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: theme.colorScheme.onSurfaceVariant,
                    ),
                  ),
                ],
              ],
            ),
          ],
        ),
      );
    }
    if (line.startsWith('### ')) {
      return Padding(
        padding: const EdgeInsets.only(top: 12, bottom: 4),
        child: Text(
          line.substring(4),
          style: theme.textTheme.titleMedium?.copyWith(
            color: theme.colorScheme.primary,
          ),
        ),
      );
    }
    if (line.startsWith('# ')) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 12),
        child: Text(line.substring(2), style: theme.textTheme.headlineSmall),
      );
    }
    if (line.startsWith('- ')) {
      final style = theme.textTheme.bodyMedium;
      return Padding(
        padding: const EdgeInsets.only(left: 8, bottom: 4),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('•  '),
            Expanded(
              child: Text.rich(
                TextSpan(children: _inlineSpans(line.substring(2), style)),
              ),
            ),
          ],
        ),
      );
    }
    if (line.trim().isEmpty) {
      return const SizedBox(height: 4);
    }
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: Text.rich(
        TextSpan(children: _inlineSpans(line, theme.textTheme.bodyMedium)),
      ),
    );
  }

  /// Renders inline `**bold**` markdown spans within a single line.
  List<InlineSpan> _inlineSpans(String text, TextStyle? style) {
    final spans = <InlineSpan>[];
    final boldPattern = RegExp(r'\*\*(.+?)\*\*');
    var cursor = 0;
    for (final match in boldPattern.allMatches(text)) {
      if (match.start > cursor) {
        spans.add(TextSpan(text: text.substring(cursor, match.start)));
      }
      spans.add(
        TextSpan(
          text: match.group(1),
          style: style?.copyWith(fontWeight: FontWeight.bold),
        ),
      );
      cursor = match.end;
    }
    if (cursor < text.length) {
      spans.add(TextSpan(text: text.substring(cursor)));
    }
    return [TextSpan(style: style, children: spans)];
  }
}
