import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

import 'package:just_in_time/core/i18n/gen/app_localizations.dart';

/// Displays the project's `CHANGELOG.md`, bundled as a Flutter asset so the
/// running app can show its own release history without anyone needing the
/// repo checked out. The file itself is generated by
/// `tool/version_bump.dart` from Conventional Commits (STACK.md §10.4) —
/// this screen only renders it, never edits it.
class ChangelogScreen extends StatelessWidget {
  /// Creates the changelog screen.
  const new({super.key});

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    return Scaffold(
      appBar: AppBar(title: Text(l10n.changelogScreenTitle)),
      body: FutureBuilder<String>(
        future: rootBundle.loadString('CHANGELOG.md'),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(child: Text(l10n.changelogLoadError));
          }
          if (!snapshot.hasData) {
            return const Center(child: CircularProgressIndicator());
          }
          return _ChangelogBody(markdown: snapshot.data!);
        },
      ),
    );
  }
}

class _ChangelogBody extends StatelessWidget {
  const new({required this.markdown});

  final String markdown;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final lines = markdown.split('\n');
    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: lines.length,
      itemBuilder: (context, index) => _lineWidget(lines[index], theme),
    );
  }

  Widget _lineWidget(String line, ThemeData theme) {
    if (line.startsWith('### ')) {
      return Padding(
        padding: const EdgeInsets.only(top: 12, bottom: 4),
        child: Text(
          line.substring(4),
          style: theme.textTheme.titleMedium?.copyWith(
            color: theme.colorScheme.primary,
          ),
        ),
      );
    }
    if (line.startsWith('## ')) {
      return Padding(
        padding: const EdgeInsets.only(top: 20, bottom: 8),
        child: Text(line.substring(3), style: theme.textTheme.titleLarge),
      );
    }
    if (line.startsWith('# ')) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 12),
        child: Text(line.substring(2), style: theme.textTheme.headlineSmall),
      );
    }
    if (line.startsWith('- ')) {
      return Padding(
        padding: const EdgeInsets.only(left: 8, bottom: 4),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('•  '),
            Expanded(
              child: Text(line.substring(2), style: theme.textTheme.bodyMedium),
            ),
          ],
        ),
      );
    }
    if (line.trim().isEmpty) {
      return const SizedBox(height: 4);
    }
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: Text(line, style: theme.textTheme.bodyMedium),
    );
  }
}
